<?php

/**
 * @file
 * Theme functions for the vegandj theme.
 */
/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function vegandj_theme_suggestions_field_alter(&$suggestions, array $variables) {
  $element = $variables['element'];

  $no_wrappers = [
    'field_media_image',
  ];

  if (in_array($element['#field_name'], $no_wrappers)) {
    $suggestions[] = 'field__no_wrappers';
  }
}
